services:
  api:
    build: backend
    command: >
      sh -c "npx drizzle-kit push && npm run buildev"
    volumes:
      - ./backend:/app/
      - /app/node_modules
    ports:
      - "3001:3001"
      - "4983:4983"
    depends_on:
      - db
      - cache
    environment:
      DATABASE_URL: postgres://sr:sr@db/schoolregister
      REDIS_URL: redis://localhost/
      PORT: 3001
      JWT_SECRET: DO_NOT_USE_DEV_IN_PROD_UNSAFE_JWT_KEY
      TURNSTILE_SITE_KEY: 1x00000000000000000000AA
      TURNSTILE_SECRET_KEY: 1x0000000000000000000000000000000AA

  web:
    build:
        context: frontend
        dockerfile: dev.Dockerfile
    command: npm run dev
    volumes:
      - ./frontend:/app/
      - /app/node_modules
    environment:
      NODE_ENV: development
      JWT_SECRET: DO_NOT_USE_DEV_IN_PROD_UNSAFE_JWT_KEY
    ports:
      - "3000:3000"
    depends_on:
      - api
    develop:
      watch:
        - action: sync
          path: ./app/frontend
          target: ./frontend

  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sr
      POSTGRES_PASSWORD: sr
      POSTGRES_DB: schoolregister

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
  postgres-data:
    driver: local